version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
  nginx:
      image: nginx:stable
      restart: always
      ports: 
          - target: 80         # inner port
            published: 80      # host os port
            protocol: tcp      # port protocal
          - target: 443        # inner port
            published: 443     # host os port
            protocol: tcp      # port protocal
      volumes:
          - ./nginx/log:/var/log/nginx/
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/ssl:/ssl
volumes:
  hapi-fhir-mysql:
