version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
  fhir-postgres:
    image: postgres:15.1
    #container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "hapi_dstu3"
      POSTGRES_USER: "DTxUser"
      POSTGRES_PASSWORD: "Khmc1803!"
    volumes:
      - /product/postgresql/data:/var/lib/postgresql/data
  nginx:
      image: nginx:stable
      restart: always
      ports: 
          - target: 80         # inner port
            published: 80      # host os port
            protocol: tcp      # port protocal
          - target: 443        # inner port
            published: 443     # host os port
            protocol: tcp      # port protocal
      volumes:
          - ./nginx/log:/var/log/nginx/
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/ssl:/ssl
volumes:
  hapi-fhir-mysql:
